services:
  referal:
    image: referal
    container_name: referal
    build:
      context: .
      dockerfile: Dockerfile
    labels:
      - "nginx.auth=true"
    volumes:
      - ./instance:/app/instance
      - ./templates:/app/templates
      - ./static:/app/static
      - ./documents:/app/documents
    env_file:
      - .env
    networks:
      - service_network     # Только внутренняя сеть сервисов
    healthcheck:
      test: ["CMD", "python", "-c", "import requests; requests.get('http://localhost:80/health', timeout=5)"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 20s

networks:
  service_network:
    external: true
    name: service_network